id: P010776
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4193
  title: རྡོ་རྗེ་འཛིན་པ་ཆེན་པོ་བསོད་ནམས་འོད་ཟེར་གྱི་རྣམ་ཐར་སྙན་ཚིག་འདོད་འཇོའི་འཁྲི་ཤིང་
  author: ''
  volumes:
    fe968add45aa42eda5500179bd7763d9:
      image_group_id: I1PD96709
      title: ''
      volume_number: 1
      total_pages: 56
