id: I7A89A8B8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:11:07+00:00'
last_modified: '2022-06-08T17:26:41.278209+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4193
  title: རྡོ་རྗེ་འཛིན་པ་ཆེན་པོ་བསོད་ནམས་འོད་ཟེར་གྱི་རྣམ་ཐར་སྙན་ཚིག་འདོད་འཇོའི་འཁྲི་ཤིང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B779:
      image_group_id: I1PD96709
      title: ''
      total_pages: 56
      order: 1
      base_file: B779.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
