id: I7A89A8B8
legacy_id: P010776
ocr_import_info:
  bdrc_scan_id: W1KG4193
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T21:10:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:24:16.120270+00:00'
last_modified: 2022-08-31 23:24:21.101826
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4193
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4193
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྡོ་རྗེ་འཛིན་པ་ཆེན་པོ་བསོད་ནམས་འོད་ཟེར་གྱི་རྣམ་ཐར་སྙན་ཚིག་འདོད་འཇོའི་འཁྲི་ཤིང་།
  author: འབྲུག་པ་ལོ་ཙཱ་བ་ངག་དབང་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.5480064372699749
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I1PD96709:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96709
      total_pages: 56
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD96709.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5480064372699749
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
